# Generated by Django 5.1.3 on 2025-04-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0009_commande_vendeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
