# Generated by Django 5.1.3 on 2025-04-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0010_commande_montant_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En Attente'), ('termine', 'Terminé')], default='en_attente', max_length=20),
        ),
    ]
