# Generated by Django 5.1.3 on 2025-04-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0011_commande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lue',
            field=models.BooleanField(default=False),
        ),
    ]
