# Generated by Django 5.1.3 on 2025-04-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0013_alter_produit_vendeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
    ]
