# Generated by Django 5.1.3 on 2025-04-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0014_produit_est_supprime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='vendeur',
        ),
    ]
