# Generated by Django 5.1.3 on 2025-04-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0016_add_reference_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
