# Generated by Django 5.1.3 on 2025-04-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0017_commande_qr_code_alter_commande_montant_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='statut_paiement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
    ]
