# Generated by Django 5.1.3 on 2025-05-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0021_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_adresse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
