# Generated by Django 5.2 on 2025-06-05 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0023_userprofile_date_joined'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vente',
            old_name='date',
            new_name='date_vente',
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='total',
            new_name='montant',
        ),
        migrations.AddField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(default='Stripe', max_length=50),
        ),
        migrations.AddField(
            model_name='vente',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
