# Generated by Django 5.2 on 2025-06-05 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0024_rename_date_vente_date_vente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.commande'),
        ),
    ]
