# Generated by Django 5.2 on 2025-06-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0025_vente_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='lue',
        ),
    ]
