# Generated by Django 5.2 on 2025-06-09 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0026_remove_notification_lue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='boutique.produit'),
        ),
    ]
